
this : line stays
# This line should not be removed

# Neither this

variable = value		# This comment should be kept

target : prerequisite		# And this one also.
	recipe

# No other line should be removed

