
	/* Suppose we receive the argument in %cx. */

	.global printf
	.code16gcc
	
printf:	

	mov %cx, %bx
	
        mov   $0x0e,%ah               
        mov   $0x0, %si               
loop:                                 
        mov   (%bx, %si), %al           
        cmp   $0x0, %al               
        je    end                    
        int   $0x10                   
        add   $0x1, %si               
        jmp   loop                    

end:                               
        ret




