#!/usr/bin/env bash

#    SPDX-FileCopyrightText: 2021 Monaco F. J. <monaco@usp.br>
#   
#    SPDX-License-Identifier: GPL-3.0-or-later
#
#    This file is part of SYSeg, available at https://gitlab.com/monaco/syseg.

# Install a custom version of reuse-tool.
#
# This is a workaround to be deprecated as soon as the mainstream
# reuse-tool repository receives the needed patches.

# PIPX_HOME=$(pwd)/.local \
# PIPX_BIN_DIR=$(pwd)/.local/bin pipx \
# install --force git+https://github.com/monacofj/reuse-tool@prod

PIPX_HOME=$HOME/.syseg \
PIPX_BIN_DIR=$HOME/.syseg/bin pipx \
install --force git+https://github.com/monacofj/reuse-tool@prod
